version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    links:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
  db:
    platform: linux/amd64
    container_name: db
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - '3307:3306'
  redis:
    image: redis:7.0-rc-alpine