version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: 'composer install && php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    links:
      - mysql
      - redis
    ports:
      - '8000:8000'
    env_file:
      - .env
  mysql:
    platform: linux/amd64
    container_name: mysql
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./storage/mysqldata:/var/lib/mysql
    ports:
      - '3307:3306'
    env_file:
      - .env
  redis:
    image: redis:7.0-rc-alpine
