on: push
name: Template Variables in Markdown
jobs:
  markdown:
    name: markdown-marker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: bdougie/variables-in-markdown@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
